apiVersion: v1
kind: Service
metadata:
    name: "kmac2-60fd"
    labels:
        app: "kmac2-60fd"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kmac2-60fd"