on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n torxic25 -g torxic25a4cf-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n torxic25 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n torxic25 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n torxic25 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: torxic25.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t torxic25.azurecr.io/kmac2:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push torxic25.azurecr.io/kmac2:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_kmac2_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kmac28f06 | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kmac28f06`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kmac28f06
        container-registry-url: torxic25.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: kmac2dockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: kmac28f06
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          torxic25.azurecr.io/kmac2:${{ github.sha }}
        imagepullsecrets: |
          kmac2dockerauth   
